import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{})});
const errors=[];const page=await browser.newPage({viewport:{width:1440,height:1100}});
page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_URL||'http://127.0.0.1:5189';
const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ashen-covenant-save-v1')));
const click=sel=>page.locator(sel).first().click();
await page.goto(base);await page.waitForTimeout(12000);
assert.ok((await read()).kills>=1,'real-time hunt advances');
await click('[data-act="pause"]');const paused=await read();await page.waitForTimeout(1100);await click('#save-btn');assert.equal((await read()).progress,paused.progress,'pause stops progress');
await click('nav [data-page="build"]');await click('[data-class="witch"]');await click('[data-build="storm"]');assert.equal((await read()).buildId,'storm');
await click('nav [data-page="inventory"]');await click('[data-item="storm-coat"]');await click('[data-equip="storm-coat"]');assert.equal((await read()).equipment.armor.id,'storm-coat');
await click('[data-item="bone-scythe"]');await click('[data-list="bone-scythe"]');assert.ok((await read()).listings.some(l=>l.owner==='you'));
await click('nav [data-page="market"]');await page.screenshot({path:'artifacts/market.png',fullPage:true});await click('[data-cancel]');assert.ok((await read()).inventory.some(i=>i.id==='bone-scythe'));
const beforeGold=(await read()).gold;await click('[data-buy="market-2"]');assert.equal((await read()).gold,beforeGold-350);assert.ok((await read()).inventory.some(i=>i.id==='market-frost'));
await click('nav [data-page="fish"]');await click('[data-activity="fish"]');assert.equal((await read()).running,true);await click('nav [data-page="adventure"]');await page.waitForTimeout(10000);await click('#save-btn');assert.ok((await read()).fish>=1,'real-time fishing');
await click('nav [data-page="fish"]');await page.screenshot({path:'artifacts/fishing.png',fullPage:true});await click('[data-act="consumeFish"]');assert.equal((await read()).fish,0);
await click('nav [data-page="boss"]');await click('[data-activity="boss"]');const hp=(await read()).boss.hp;await page.waitForTimeout(2100);await click('#save-btn');assert.ok((await read()).boss.hp<hp);await page.screenshot({path:'artifacts/boss.png',fullPage:true});
await click('nav [data-page="adventure"]');await click('[data-zone="grave"]');assert.equal((await read()).activity,'hunt');
await page.screenshot({path:'artifacts/desktop.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.reload();await page.waitForTimeout(1000);assert.equal((await read()).buildId,'storm','reload preserves build');
await page.addInitScript(()=>{if(sessionStorage.getItem('offline-test-done'))return;const s=JSON.parse(localStorage.getItem('ashen-covenant-save-v1'));if(s){s.savedAt=Date.now()-120000;localStorage.setItem('ashen-covenant-save-v1',JSON.stringify(s));sessionStorage.setItem('offline-test-done','yes');}});await page.reload();await page.waitForTimeout(500);assert.match((await read()).offlineSummary,/离线 2 分钟/);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile width');
for(const tab of ['build','inventory','boss','fish','market','adventure']){await click(`nav [data-page="${tab}"]`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,tab+' mobile overflow');}
await click('nav [data-page="inventory"]');await click('[data-item="bone-scythe"]');await page.screenshot({path:'artifacts/mobile-item.png',fullPage:true});await click('[data-close]');
assert.deepEqual(errors,[]);
await fs.writeFile('artifacts/browser-results.json',JSON.stringify({passed:true,checks:['real-time hunt','pause','class/build','equip','list/cancel','purchase balance','real-time fish/redeem','boss damage','return hunt','reload','offline rewards','6 mobile pages','item modal'],errors,viewports:['1440x1100','390x844'],url:base},null,2));
console.log('Production browser checks passed; 14 behavior/layout checks, no page errors.');await browser.close();
