import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const out = 'artifacts/v04';
await fs.mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, recordVideo: { dir: `${out}/motion`, size: { width: 1440, height: 1050 } } });
  const page = await context.newPage(), errors = [], checks = [];
  page.on('pageerror', error => errors.push(error.message));
  const click = selector => page.locator(selector).first().click();
  const nav = tab => click(`nav [data-page="${tab}"]`);
  const base = process.env.TEST_URL || 'http://127.0.0.1:5189';
  await page.goto(base);
  await page.waitForSelector('#encounter-name');
  assert.equal(await page.evaluate(() => Boolean(window.__ASHEN__)), false, 'production debug hooks absent');
  assert.match(await page.locator('#encounter-name').textContent(), /断钟守墓人/);
  const fullHp = await page.locator('#encounter-hp').textContent();
  await page.waitForFunction(hp => document.querySelector('#encounter-hp').textContent !== hp, fullHp);
  assert.match(await page.locator('#encounter-phase').textContent(), /自动交战/);
  await page.screenshot({ path: `${out}/desktop-combat.png`, fullPage: true });
  await page.waitForFunction(() => document.querySelector('#encounter-phase').textContent === '敌人倒下');
  assert.match(await page.locator('#encounter-hp').textContent(), /^0 \/ /);
  assert.match(await page.locator('#scene-caption').textContent(), /已倒下/);
  await page.locator('#scene-panel').screenshot({ path: `${out}/defeat.png` });
  await page.waitForFunction(() => !document.querySelector('#encounter-name').textContent.includes('断钟守墓人'));
  checks.push('real hit/death/new enemy cycle');
  await click('[data-act="pause"]');
  const pausedHp = await page.locator('#encounter-hp').textContent();
  await page.waitForTimeout(800);
  assert.equal(await page.locator('#encounter-hp').textContent(), pausedHp);
  assert.equal(await page.locator('#encounter-phase').textContent(), '远征暂停');
  checks.push('pause freezes combat');
  await nav('journal');
  assert.equal(await page.locator('[data-monster]').count(), 3);
  assert.equal(await page.locator('.locked-chapter').count(), 3);
  assert.equal(await page.locator('.bestiary-card img').evaluateAll(images => images.every(i => i.complete && i.naturalWidth > 0)), true);
  await page.waitForFunction(() => !document.querySelector('#toast').classList.contains('show'));
  await page.screenshot({ path: `${out}/journal.png`, fullPage: true });
  checks.push('level-gated lore and actual monster art');
  await nav('settings');
  await click('[data-setting="muted"]');
  assert.equal(await page.locator('[data-setting="muted"]').getAttribute('aria-pressed'), 'true');
  await page.locator('#volume-slider').focus();
  await page.keyboard.press('Home');
  for (let n = 0; n < 13; n++) await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('#volume-output').textContent(), '65%');
  await page.waitForTimeout(1100);
  assert.equal(await page.locator('#volume-slider').evaluate(el => el === document.activeElement), true);
  await click('[data-setting="reducedMotion"]');
  await page.reload(); await nav('settings');
  assert.equal(await page.locator('[data-setting="muted"]').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('[data-setting="reducedMotion"]').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('#volume-output').textContent(), '65%');
  checks.push('keyboard volume, stable focus and settings persist');
  await page.screenshot({ path: `${out}/settings.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  for (const tab of ['adventure', 'build', 'inventory', 'boss', 'fish', 'market', 'journal', 'settings']) {
    await nav(tab);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${tab}: page overflow`);
  }
  await page.screenshot({ path: `${out}/mobile-settings.png`, fullPage: true });
  await nav('adventure'); await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `${out}/mobile-combat.png`, fullPage: true });
  checks.push('eight mobile pages, scrolling navigation');
  assert.deepEqual(errors, []);
  await context.close();
  await fs.writeFile(`${out}/results.json`, JSON.stringify({ passed: true, checks, errors, url: base, recordedAt: new Date().toISOString() }, null, 2));
  console.log(JSON.stringify({ passed: true, checks, errors }));
} finally { await browser.close(); }
