import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { createGame, SAVE_KEY } from '../src/engine.js';

const out = 'artifacts/v06';
await fs.mkdir(out, { recursive: true });
const base = process.env.TEST_URL || 'http://127.0.0.1:5189';
const browser = await chromium.launch({ headless: true });
const errors = [], checks = [];
const fresh = () => {
  const game = createGame(null);
  Object.assign(game.state, { running: false, savedAt: Date.now(), gold: 100000, shards: 1000 });
  return structuredClone(game.state);
};
async function fixture(state) {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
  await context.addInitScript(({ state, key }) => {
    if (sessionStorage.getItem('forge-fixture')) return;
    localStorage.setItem(key, JSON.stringify(state));
    sessionStorage.setItem('forge-fixture', 'yes');
  }, { state, key: SAVE_KEY });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base); await page.waitForSelector('nav');
  const click = selector => page.locator(selector).first().click();
  const read = () => page.evaluate(key => JSON.parse(localStorage.getItem(key)), SAVE_KEY);
  await click('nav [data-page="inventory"]');
  return { context, page, click, read };
}
try {
  const old = fresh();
  delete old.balanceVersion;
  Object.assign(old, { level: 85, xp: 1527 });
  const first = await fixture(old);
  const { page, read, click } = first;
  const migrated = await read();
  assert.equal(migrated.level, 85);
  assert.equal(migrated.gold, old.gold); assert.equal(migrated.shards, old.shards);
  assert.equal(migrated.balanceVersion, 1);
  assert.equal(await page.locator('.balance-notice').count(), 1);
  await click('[data-dismiss-migration]');
  assert.equal(await page.locator('.balance-notice').count(), 0);
  assert.ok(migrated.xp > old.xp, 'migration preserves the completed proportion of the larger threshold');
  assert.equal(migrated.inventory.length, old.inventory.length);
  await page.reload(); await click('nav [data-page="inventory"]');
  assert.equal((await read()).xp, migrated.xp, 'migration runs once');
  checks.push('85-level legacy save preserves wealth/items and migrates level progress exactly once');

  await click('[data-item="ember-blade"]');
  await click('[data-forge-panel] summary');
  const before = await read();
  assert.equal(Number((await page.locator('[data-forge-before]').textContent()).replace('%', '')), 18);
  assert.equal(Number((await page.locator('[data-forge-after]').textContent()).replace('%', '')), 21);
  assert.equal((await read()).rng, before.rng);
  assert.equal((await read()).gold, before.gold, 'opening a quote spends nothing');
  await page.locator('[data-forge-panel]').scrollIntoViewIfNeeded();
  await page.screenshot({ path: `${out}/forge-desktop.png`, fullPage: false });
  await click('[data-forge="ember-blade"]');
  const forged = await read();
  assert.equal(forged.gold, before.gold - 320);
  assert.equal(forged.shards, before.shards - 20);
  assert.equal(forged.equipment.weapon.bonus, 21);
  assert.equal(forged.equipment.weapon.forgeRank, 1);
  assert.equal(forged.inventory.find(i => i.id === 'ember-blade').bonus, 21);
  assert.equal(forged.rng, before.rng);
  assert.equal(await page.locator('[data-forge-panel]').getAttribute('open'), null, 'a successful upgrade collapses the forge before another purchase');
  await click('[data-lock="ember-blade"]');
  await click('[data-forge-panel] summary');
  assert.equal(await page.locator('[data-forge="ember-blade"]').isDisabled(), true);
  assert.match(await page.locator('.forge-status').textContent(), /锁/);
  await click('[data-lock="ember-blade"]');
  await click('[data-forge-panel] summary');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('[data-forge="ember-blade"]').scrollIntoViewIfNeeded();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.equal(await page.locator('#modal').evaluate(el => el.scrollWidth > el.clientWidth), false);
  await page.screenshot({ path: `${out}/forge-mobile.png`, fullPage: false });
  await click('[data-forge="ember-blade"]');
  assert.equal((await read()).equipment.weapon.forgeRank, 2);
  await click('[data-close]'); await page.reload();
  assert.equal((await read()).equipment.weapon.forgeRank, 2);
  checks.push('real forge purchase, exact costs, equipped reference, pure preview, lock, repeat-click protection and mobile persistence');
  await first.context.close();

  const poor = fresh(); poor.shards = 0; poor.gold = 0;
  const second = await fixture(poor);
  await second.click('[data-item="ember-blade"]'); await second.click('[data-forge-panel] summary');
  assert.equal(await second.page.locator('[data-forge="ember-blade"]').isDisabled(), true);
  assert.equal(await second.page.locator('.forge-costs .short').count(), 2);
  await second.context.close();
  const stored = fresh();
  stored.vault.push({ ...structuredClone(stored.inventory[5]), id: 'vault-forge', forgeRank: 4, locked: false });
  const third = await fixture(stored);
  await third.click('[data-storage="vault"]'); await third.click('[data-item="vault-forge"]');
  await third.click('[data-forge-panel] summary'); await third.click('[data-forge="vault-forge"]');
  const finished = await third.read();
  assert.equal(finished.vault[0].forgeRank, 5);
  assert.equal(finished.inventory.length, stored.inventory.length);
  assert.equal(finished.equipment.ring.id, stored.equipment.ring.id, 'vault forging does not auto-equip');
  await third.click('[data-forge-panel] summary');
  assert.equal(await third.page.locator('[data-forge="vault-forge"]').count(), 0);
  assert.equal(await third.page.locator('.forge-complete').count(), 1);
  checks.push('insufficient funds are visible; vault forging preserves ownership and the five-rank limit');
  await third.context.close();

  const live = fresh();
  Object.assign(live, { running: true, activity: 'boss', shards: 12 });
  live.boss.hp = 6000;
  const fourth = await fixture(live);
  await fourth.click('[data-item="ember-blade"]');
  await fourth.click('[data-forge-panel] summary');
  assert.equal(await fourth.page.locator('[data-forge="ember-blade"]').isDisabled(), true);
  await fourth.page.locator('[data-forge="ember-blade"]:not([disabled])').waitFor({ timeout: 25000 });
  assert.equal(await fourth.page.locator('[data-forge-panel]').getAttribute('open'), '');
  const liveShards = Number((await fourth.page.locator('#shards').textContent()).replaceAll(',', ''));
  assert.ok(liveShards >= 20, 'the live header and open quote agree before the next periodic save');
  await fourth.click('[data-forge="ember-blade"]');
  assert.equal((await fourth.read()).equipment.weapon.forgeRank, 1);
  assert.equal((await fourth.read()).shards, liveShards - 20);
  checks.push('open forge refreshes funds and enables purchase after a real boss reward without closing the dialog');
  await fourth.context.close();
  assert.deepEqual(errors, []);
  const report = { passed: true, base, checks, errors, checkedAt: new Date().toISOString() };
  await fs.writeFile(`${out}/forge-results.json`, JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report));
} finally { await browser.close(); }
