import { createGame, CLASSES, ZONES } from './engine.js';
import { createScene } from './scene.js';
import { journalMarkup, settingsMarkup, adventureStory, updateCombatHud } from './expedition-ui.js';
import { createSettings, createAudio } from './settings.js';
import { portraitDataUrl } from './portrait.js';
import { createIcons, Flame, Swords, Network, Backpack, Skull, Fish, Scale, Save, Coins, Gem, CircleHelp, MapPin, Shield, Sparkles, ArrowUpRight, Shirt, Plus, ChevronRight, ArrowRight, Pause, Play, Timer, Church, Trees, Castle, Mountain, Check, Sword, Zap, CircleCheck, Circle, X } from 'lucide';
const icons={Flame,Swords,Network,Backpack,Skull,Fish,Scale,Save,Coins,Gem,CircleHelp,MapPin,Shield,Sparkles,ArrowUpRight,Shirt,Plus,ChevronRight,ArrowRight,Pause,Play,Timer,Church,Trees,Castle,Mountain,Check,Sword,Zap,CircleCheck,Circle,X};
import './style.css';

const game=createGame();
const preferences=createSettings();
const audio=createAudio(()=>preferences.state);
document.documentElement.dataset.reducedMotion=preferences.state.reducedMotion;
let testFrozen=false;
let page='adventure',filter='all',selected=null,toastTimer;
const $=s=>document.querySelector(s);
const icon=(name,cls='')=>`<i data-lucide="${name}" class="${cls}"></i>`;
const fmt=n=>Math.floor(n||0).toLocaleString('zh-CN');
const rarity={magic:'魔法',rare:'稀有',legendary:'传奇'};
const elements={fire:'火焰',frost:'冰霜',poison:'毒素',physical:'物理',magic:'魔法',shadow:'暗影',lightning:'闪电'};
const slotNames={weapon:'武器',armor:'护甲',ring:'戒指'};
const itemIcon=i=>icon(i.slot==='weapon'?'swords':i.slot==='armor'?'shirt':'gem');
const meter=(value,cls='')=>`<div class="meter ${cls}"><span style="width:${Math.min(100,Math.max(0,value))}%"></span></div>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function execute(type,payload){try{const message=game.act(type,payload);if(message)toast(message);game.save();render();}catch(e){toast('操作未完成：'+e.message);}}

$('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#">${icon('flame')}<span>灰烬契约<small>ASHEN COVENANT</small></span></a><div class="season"><span class="status-dot"></span> 永夜纪元 <b>序章</b></div><div class="nav-label">烬灯堡</div><nav>${[['adventure','swords','冒险征途'],['build','network','职业与流派'],['inventory','backpack','行囊与装备'],['boss','skull','世界首领'],['fish','fish','幽潭垂钓'],['market','scale','交易行'],['journal','church','余烬档案'],['settings','circle-help','旅途设置']].map(([id,i,n])=>`<button data-page="${esc(id)}">${icon(i)}<span>${n}</span>${id==='boss'?'<em>世界</em>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="rune">✧</div><p>余烬未熄，征途不止。</p><small>像素放置 RPG · 本地试玩版</small><button id="save-btn">${icon('save')} 保存进度</button><span class="save-note">自动存档 · 离线收益上限 8 小时</span></div></aside>
<div class="workspace"><header><div class="breadcrumb">烬灯堡 <span>/</span> <b id="breadcrumb">冒险征途</b></div><div class="currencies"><span>${icon('coins')} <b id="gold"></b><small>金币</small></span><span>${icon('gem')} <b id="shards"></b><small>余烬</small></span><button id="help-btn" aria-label="游戏说明">${icon('circle-help')}</button></div></header><main><section class="page-heading"><div><div class="eyebrow">THE LONG NIGHT · 不息的远征</div><h1 id="title">冒险征途</h1><p id="subtitle">将战斗交给时间，将命运交给你的选择。</p></div><div class="live-badge"><span class="status-dot"></span><span id="live-label">自动征战中</span></div></section><div class="layout"><section class="main-column"><div id="content"></div><section class="panel scene-panel" id="scene-panel"><div class="scene-label"><span>${icon('map-pin')} <b id="scene-title"></b></span><span class="pixel-tag">LIVE EXPEDITION</span></div><div id="scene"></div><div id="encounter-hud" class="encounter-hud"><div class="encounter-top"><b id="encounter-name" class="encounter-name"></b><span id="encounter-phase" class="encounter-tag"></span></div><div class="enemy-meter" role="progressbar" aria-label="当前敌人生命" aria-valuemin="0" aria-valuemax="100" id="enemy-meter"><span id="enemy-health"></span></div><div class="encounter-bottom"><span id="encounter-trait"></span><b id="encounter-hp"></b></div></div><div class="scene-caption"><span id="scene-caption"></span><span>自动战斗 · 无需操作</span></div></section><div id="below"></div></section><aside class="character-column" id="character"></aside></div><footer><span id="save-status"><i class="status-dot"></i> 本机存档已启用</span><span>无需追赶时间，成长自会发生。</span><span>v0.4 · 世界与市场为本地模拟</span></footer></main></div><div id="toast" role="status"></div><dialog id="modal"></dialog>`;
const scene=createScene($('#scene'),()=>testFrozen?{...game.state,running:false}:game.state,()=>game.combat(),id=>game.eventsSince(id),()=>preferences.state);
function current(){const s=game.state;const c=CLASSES.find(c=>c.id===s.classId)||CLASSES[0];return {s,c,b:c.builds.find(b=>b.id===s.buildId)||c.builds[0],z:ZONES.find(z=>z.id===s.zoneId)||ZONES[0],stats:game.stats()};}
function character(){const {s,c,b,stats}=current();$('#character').innerHTML=`<section class="panel character"><div class="panel-title"><h2>契约者</h2><span class="small-tag">${esc(c.name)}</span></div><div class="portrait"><img class="hero-portrait" src="${portraitDataUrl(s.classId)}" alt="${esc(c.name)}像素肖像"><div class="portrait-sigil">✧</div><span class="level-badge">${s.level}</span></div><h3>无名的余烬</h3><div class="character-sub">${esc(c.name)} <span>·</span> ${esc(b.name)}</div><div class="xp-row"><span>等级 ${s.level}</span><span>${fmt(s.xp)} / ${fmt(stats.xpNext)}</span></div>${meter(s.xp/stats.xpNext*100,'xp')}<div class="stat-grid"><div>${icon('swords')}<span title="用于装备与流派比较；清剿效率还计入范围、抗性和休整，首领伤害单独结算。">面板伤害</span><b>${fmt(stats.dps)}</b></div><div>${icon('shield')}<span>防御</span><b>${fmt(stats.defense)}</b></div><div>${icon('sparkles')}<span>寻宝加成</span><b>${fmt(stats.magicFind)}%</b></div><div>${icon('flame')}<span>流派属性</span><b>${elements[b.element]||b.element}</b></div><div>${icon('network')}<span>待分配技能点</span><b>${stats.skillPoints??0}</b></div></div><div class="section-label">当前装备 <button data-page="inventory">管理 ${icon('arrow-up-right')}</button></div><div class="equipped">${['weapon','armor','ring'].map(slot=>{const it=s.equipment[slot];return `<button data-item="${esc(it?.id||'')}" class="equipment ${it?.rarity||''}"><span class="item-square">${it?itemIcon(it):icon('plus')}</span><span><b>${esc(it?.name||'空装备位')}</b><small>${slotNames[slot]} · ${it?rarity[it.rarity]:'未装备'}</small></span>${icon('chevron-right')}</button>`;}).join('')}</div><button class="outline wide" data-page="build">${icon('network')} 调整我的流派</button></section><section class="quote-panel"><span>“</span><p>深渊不曾凝视你。<br>它只是在等待下一个传说。</p><small>— 烬灯堡残卷</small></section>`;}
function lootRows(items){return items.map(it=>`<button class="loot-row ${it.rarity}" data-item="${esc(it.id)}"><span class="item-square">${itemIcon(it)}</span><span><b>${esc(it.name)}</b><small>${slotNames[it.slot]} · ${elements[it.element]||it.element}</small></span><em>${rarity[it.rarity]}</em><span class="power">${fmt(it.power)} <small>威能</small></span>${icon('chevron-right')}</button>`).join('')||'<div class="empty">下一件珍宝，正在路上。</div>';}
function adventure(){const {s,z,stats}=current();$('#content').innerHTML=`<div class="chapter-strip"><span class="chapter-number">I</span><div><small>第一幕 · 最后的守火者</small><h2>${esc(z.name)}</h2></div><span class="chapter-meta">推荐等级 ${z.level}<br><small>${elements[z.element]||'无'}抗性区域</small></span></div>`;$('#below').innerHTML=`<section class="panel expedition"><div class="panel-title"><h2><span class="status-dot"></span> ${s.activity==='hunt'?'正在清剿':s.activity==='boss'?'正在讨伐首领':'正在垂钓'}</h2><button class="text-button" data-act="pause">${icon(s.running?'pause':'play')} ${s.running?'暂停挂机':'继续挂机'}</button></div><div class="progress-label"><span>${s.activity==='hunt'?'追猎、战斗与自动拾取':s.activity==='boss'?'共同削弱深渊领主':'静候幽潭的馈赠'}</span><b id="run-progress">${Math.floor(s.progress*100)}%</b></div><div class="meter" id="run-meter"><span style="width:${s.progress*100}%"></span></div><div class="run-stats"><span>${icon('swords')} 已击败 <b>${fmt(s.kills)}</b></span><span>${icon('timer')} 预计每轮 <b>${Math.round(stats.huntSeconds||z.seconds)} 秒</b></span><span>${icon('backpack')} 行囊 <b>${s.inventory.length}/60</b></span></div></section><section class="panel"><div class="panel-title"><h2>远征地点</h2><span class="muted">选择适合流派的猎场</span></div><div class="zones">${ZONES.map((zone,i)=>`<button class="zone ${s.zoneId===zone.id?'selected':''}" data-zone="${zone.id}"><span class="zone-icon">${icon(['church','trees','castle','mountain'][i%4])}</span><b>${esc(zone.name)}</b><small>Lv.${zone.level} · ${elements[zone.element]||'无'}抗性</small><em>${zone.level>s.level?'Lv.'+zone.level+' 解锁':s.zoneId===zone.id?'当前征途':'前往征战'} ${icon(s.zoneId===zone.id?'check':'arrow-right')}</em></button>`).join('')}</div></section><section class="panel"><div class="panel-title"><h2>新获战利品 <span class="tiny">RECENT LOOT</span></h2><button data-page="inventory" class="text-button">全部战利品 ${icon('arrow-right')}</button></div>${lootRows(s.inventory.slice(-4).reverse())}</section><section class="panel chronicle"><div class="panel-title"><h2>征途手记</h2><span class="muted">自动记录最近的收获</span></div>${s.logs.slice(0,4).map((l,i)=>`<p><span>${i===0?'刚刚':'·'}</span>${esc(l)}</p>`).join('')}</section>`;}
function build(){
  const {s,c,b,stats}=current();
  const ranks=s.talents?.[c.id]||{};
  const skillSymbols={combat:'swords',mastery:'shield',warcries:'network',fire:'flame',cold:'sparkles',lightning:'zap'};
  $('#content').innerHTML=`
    <section class="panel class-selection">
      <div class="panel-title"><h2>选择职业</h2><span class="small-tag">首发 · 两大职业</span></div>
      <div class="class-list class-list-two">${CLASSES.map(cl=>`<button class="class-choice ${cl.id===s.classId?'selected':''}" data-class="${esc(cl.id)}" aria-pressed="${cl.id===s.classId}">
        <img class="class-portrait" src="${portraitDataUrl(cl.id)}" alt="${esc(cl.name)}">
        <div class="class-description"><small>${cl.id==='barbarian'?'BARBARIAN':'SORCERESS'}</small><h3>${esc(cl.name)}</h3><p>${esc(cl.subtitle)}</p><span>${cl.id===s.classId?'当前职业 · 已选择':'选择职业 →'}</span></div>
      </button>`).join('')}</div>
      <p class="note">可自由切换职业，等级与装备保留；两个职业分别保存自己的技能加点。</p>
    </section>
    <section class="panel">
      <div class="panel-title"><h2>${esc(c.name)} · 挂机流派</h2><span class="muted">选择流派后自动施放</span></div>
      <div class="build-presets">${c.builds.map(preset=>`<button class="preset ${preset.id===b.id?'selected':''}" data-build="${esc(preset.id)}" aria-pressed="${preset.id===b.id}">
        <span class="preset-top">${icon(preset.element==='fire'?'flame':preset.element==='frost'?'sparkles':preset.element==='lightning'?'zap':preset.element==='magic'?'network':'swords')}<small>${esc(preset.role||elements[preset.element])}</small>${icon(preset.id===b.id?'circle-check':'circle')}</span>
        <h3>${esc(preset.name)}</h3><p>${esc(preset.desc)}</p><span class="preset-element">${elements[preset.element]}伤害</span>
      </button>`).join('')}</div>
      <div class="auto-loadout"><span class="section-label">流派技能协同</span><div class="rotation">${(b.skills||[b.name]).map(name=>`<span><em>${name===b.name?'主攻':'协同'}</em>${esc(name)}</span>`).join('')}</div><p>主攻技能自动施放；协同与被动投入技能点后生效。<br>${esc(b.mechanic||b.desc)}</p></div>
      <div class="build-readout"><span>首领伤害 <b>${fmt(stats.bossDps||stats.dps)} / 秒</b></span><span>清怪加成 <b>+${fmt((stats.areaBonus||0)*100)}%</b></span><span>攻速倍率 <b>${(stats.attackSpeed||1).toFixed(2)}×</b></span></div>
      <p class="build-effect">${icon('sparkles')} ${b.id==='frenzy'?esc(stats.buildEffect)+' · ':''}当前猎场抗性 ${(stats.zoneResistance*100).toFixed(0)}% · 预计每轮 ${stats.huntSeconds.toFixed(1)} 秒</p>
    </section>
    <section class="panel talent-panel">
      <div class="panel-title"><h2>技能修炼</h2><span class="points-badge">可用技能点 <b id="skill-points">${stats.skillPoints??0}</b></span></div>
      <div class="talent-rules"><p>初始 3 点，每升一级获得 1 点。技能独立修炼，最高 10 级，可免费重置。</p><button class="outline" data-act="resetTalents" ${(stats.trainingSpent||0)===0?'disabled':''}>重置加点</button></div>
      <div class="talent-trees">${(c.trees||[]).map((tree,index)=>`<section class="talent-tree tree-${index}">
        <div class="tree-heading">${icon(skillSymbols[tree.id]||['swords','shield','network'][index])}<h3>${esc(tree.name)}</h3><small>${esc(tree.desc)}</small></div>
        <div class="tree-skills">${tree.skills.map(skill=>{const rank=ranks[skill.id]||0;const capped=rank>=skill.maxRank;return `<article class="talent ${rank?'learned':''}">
          <div class="talent-name"><b>${esc(skill.name)}</b><span>${rank}<small> / ${skill.maxRank}</small></span></div><p>${esc(skill.desc)}</p>
          <div class="rank-track" aria-hidden="true">${Array.from({length:skill.maxRank},(_,i)=>`<i class="${i<rank?'filled':''}"></i>`).join('')}</div>
          <button class="train-button" data-train="${esc(skill.id)}" aria-label="提升${esc(skill.name)}" ${capped||(stats.skillPoints||0)<1?'disabled':''}>${icon(capped?'check':'plus')}${capped?'已修炼至上限':'修炼 · 1 点'}</button>
        </article>`;}).join('')}</div>
      </section>`).join('')}</div>
      <p class="note">元素技能只强化对应流派，支配与防御技能提供被动收益。流派与装备亲和共同决定效率；这里是为挂机简化的技能体系。</p>
    </section>`;
  $('#below').innerHTML='';
}
function inventory(){const {s}=current();const items=s.inventory.filter(i=>filter==='all'||i.rarity===filter);$('#content').innerHTML=`<section class="panel"><div class="panel-title"><h2>旅人的行囊 <span class="tiny">${s.inventory.length} / 60</span></h2><span class="muted">点击装备查看词缀与交易价值</span></div><div class="tabs">${['all','magic','rare','legendary'].map(r=>`<button class="${filter===r?'active':''}" data-filter="${r}">${rarity[r]||'全部'}</button>`).join('')}</div><div class="inventory-list">${lootRows(items.slice().reverse())}</div><p class="note">行囊满时，新掉落自动折算为金币。已装备物品需替换后才可出售或上架。</p></section>`;$('#below').innerHTML='';}
function boss(){const {s}=current();$('#content').innerHTML=`<section class="panel boss-intro"><span class="eyebrow">WORLD ENCOUNTER · 本地模拟</span><h2>骸冠君王 · 莫尔迦斯</h2><p>永夜王座上的无名君王，正召集他的亡者军团。</p><div class="boss-health"><span>深渊生命</span><b>${fmt(s.boss.hp)} / ${fmt(s.boss.maxHp)}</b></div>${meter(s.boss.hp/s.boss.maxHp*100,'blood')}<div class="run-stats"><span>你的贡献 <b>${fmt(s.boss.contribution)}</b></span><span>已讨伐 <b>${s.boss.kills}</b> 次</span></div><button class="primary" data-activity="boss">${icon('swords')} ${s.activity==='boss'&&s.running?'正在自动讨伐':!s.running?'恢复自动讨伐':'加入自动讨伐'}</button><p class="note">演示队友会协同攻击；击败首领自动获得战利品并开始下一轮。此版本未连接其他玩家。</p></section>`;$('#below').innerHTML=`<section class="panel"><div class="panel-title"><h2>讨伐回报</h2></div><div class="reward-grid"><div>${icon('gem')}<b>随机高阶装备</b><small>打造下一套核心 Build</small></div><div>${icon('flame')}<b>余烬与经验</b><small>首领击败后自动入账</small></div></div></section>`;}
function fishing(){const {s}=current();$('#content').innerHTML=`<section class="panel fishing"><span class="eyebrow">THE SILENT WATER</span><h2>幽潭垂钓</h2><p>把纷争留在岸上。深水之下，也藏着命运的馈赠。</p><div class="fish-counter">${icon('fish')}<b>${fmt(s.fish)}</b><span>尾幽光鱼</span></div>${meter(s.activity==='fish'?s.progress*100:0,'xp')}<div class="button-row"><button class="primary" data-activity="fish">${icon('fish')} ${s.activity==='fish'&&s.running?'正在自动垂钓':!s.running?'恢复自动垂钓':'开始自动垂钓'}</button><button class="outline" data-act="consumeFish" ${s.fish<1?'disabled':''}>兑换渔获</button></div><p class="note">渔获可兑换成长资源，偶尔还能钓起失落装备。切换活动后仍会自动挂机。</p></section>`;$('#below').innerHTML='';}
function market(){const {s}=current();$('#content').innerHTML=`<section class="panel"><div class="panel-title"><h2>流亡者集市</h2><span class="small-tag">本地模拟市场</span></div><p class="note">购买演示商人的宝物，或从行囊上架你的装备。个人挂单等待撤回，不会虚构其他玩家成交。</p><div class="market-grid">${s.listings.map(l=>`<article class="market-item ${l.item.rarity}"><div class="market-item-head"><span class="item-square">${itemIcon(l.item)}</span><span class="small-tag">${l.owner==='you'?'我的挂单':rarity[l.item.rarity]}</span></div><h3>${esc(l.item.name)}</h3><p>${elements[l.item.element]} · 威能 ${l.item.power}</p><small>${esc(l.item.affixes.join(' / '))}</small><div class="market-price"><b>${icon('coins')} ${fmt(l.price)}</b><button class="outline" data-${l.owner==='you'?'cancel':'buy'}="${esc(l.id)}" ${l.owner!=='you'&&s.gold<l.price?'disabled':''}>${l.owner==='you'?'撤回':'购买'}</button></div></article>`).join('')||'<p class="empty">暂时没有挂单，可以前往行囊上架装备。</p>'}</div></section>`;$('#below').innerHTML='';}
const pages={adventure:['冒险征途','将战斗交给时间，将命运交给你的选择。',adventure],build:['职业与流派','力量没有唯一的答案。定义属于你的战斗方式。',build],inventory:['行囊与装备','一件不起眼的遗物，也许正是流派缺失的拼图。',inventory],boss:['世界首领','聚合微小的余烬，撼动深渊的王座。',boss],fish:['幽潭垂钓','长夜之中，给灵魂片刻宁静。',fishing],market:['交易行','你的多余之物，或许是另一个传说的起点。',market]};
pages.journal=['余烬档案','那些无人记得的名字，正等待你带回炉火旁。',()=>{$('#content').innerHTML=journalMarkup(game.state);$('#below').innerHTML='';}];
pages.settings=['旅途设置','让长夜保持你喜欢的节奏。',()=>{$('#content').innerHTML=settingsMarkup(preferences.state,audio);$('#below').innerHTML='';}];
function render(){
  const active=document.activeElement;
  const focusKey=active?.tagName==='BUTTON'?Array.from(active.attributes).find(a=>a.name.startsWith('data-')):null;
  const {s,z}=current();$('#save-status').textContent=s.storageAvailable===false?'存储不可用 · 当前进度未保存':'● 本机存档已启用';$('#gold').textContent=fmt(s.gold);$('#shards').textContent=fmt(s.shards);$('#title').textContent=pages[page][0];$('#breadcrumb').textContent=pages[page][0];$('#subtitle').textContent=pages[page][1];$('#live-label').textContent=s.running?({hunt:'自动征战中',boss:'自动讨伐中',fish:'自动垂钓中'}[s.activity]):'挂机已暂停';document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('active',el.dataset.page===page));pages[page][2]();if(page==='adventure')$('#content').insertAdjacentHTML('beforeend',adventureStory(s));$('#scene-panel').hidden=!['adventure','boss','fish'].includes(page);$('#scene-title').textContent=s.activity==='boss'?'永夜王座':s.activity==='fish'?'幽光湖畔':z.name;$('#scene-caption').textContent=s.running?'远征进行中':'远征已暂停';character();updateCombatHud(game);createIcons({icons});
  if(focusKey){const target=document.querySelector(`[${focusKey.name}="${CSS.escape(focusKey.value)}"]`);if(target&&!target.disabled)target.focus({preventScroll:true});}
}
function showItem(id){const {s}=current();const it=s.inventory.find(i=>i.id===id);if(!it)return;selected=id;const equipped=s.equipment[it.slot];const isEquipped=equipped?.id===it.id;$('#modal').innerHTML=`<button class="close" data-close aria-label="关闭">${icon('x')}</button><span class="eyebrow">${rarity[it.rarity]} · ${slotNames[it.slot]}</span><div class="item-detail ${it.rarity}"><span class="item-square">${itemIcon(it)}</span><h2>${esc(it.name)}</h2></div><div class="detail-power">${it.power}<small>装备威能</small></div><p>${elements[it.element]}亲和 · 流派加成 ${it.bonus}%</p><ul class="affixes">${it.affixes.map(a=>`<li>✧ ${esc(a)}</li>`).join('')}</ul><p class="note">${isEquipped?'此装备正在使用':equipped?`当前装备：${esc(equipped.name)} · 威能 ${equipped.power}，请结合词缀选择。`:'此槽位尚未装备'}</p><div class="button-row"><button class="primary" data-equip="${esc(id)}" ${isEquipped?'disabled':''}>${isEquipped?'已装备':'装备'}</button><button class="outline" data-sell="${esc(id)}" ${isEquipped?'disabled':''}>出售 · ${fmt(it.value)} 金币</button><button class="outline" data-list="${esc(id)}" ${isEquipped?'disabled':''}>上架交易行</button></div><p class="note">上架价格由装备价值计算，详见交易行；可随时撤回。</p>`;createIcons({icons});$('#modal').showModal();}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;const d=el.dataset;audio.unlock();audio.play('ui');if(d.setting){const key=d.setting;preferences.update(key,!preferences.state[key]);document.documentElement.dataset.reducedMotion=preferences.state.reducedMotion;audio.unlock();audio.sync(game.state.running);render();return;}if(d.page){page=d.page;render();return;}if(d.item){showItem(d.item);return;}if(d.filter){filter=d.filter;render();return;}if('close'in d){$('#modal').close();return;}for(const action of ['class','build','zone','activity','equip','sell','list','buy','cancel','train'])if(d[action]){execute(action,d[action]);if(['equip','sell','list'].includes(action))$('#modal').close();return;}if(d.act)execute(d.act);});
$('#save-btn').onclick=()=>{toast(game.save()?'征途已保存到本机。':'存档失败，请检查浏览器存储权限。');};
$('#help-btn').onclick=()=>{$('#modal').innerHTML=`<button class="close" data-close aria-label="关闭">×</button><span class="eyebrow">WELCOME, WANDERER</span><h2>欢迎来到灰烬契约</h2><p>选择流派与猎场后，战斗、拾取和升级都会自动完成。点击战利品比较词缀，再决定装备、出售或上架。</p><p>世界首领与钓鱼都是可切换的挂机活动，同一时间进行一种活动。关闭页面后最多结算 8 小时离线收益。</p><p>当前为本地试玩：Boss 队友与商人是模拟的，存档仅在当前浏览器中。首发职业为野蛮人和法师，职业页可选择流派和分配技能点。切换与重置免费，保留成长。</p><button class="primary" data-close>继续我的征途</button>`;$('#modal').showModal();};
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').close();});
document.addEventListener('input',event=>{if(event.target.id!=='volume-slider')return;preferences.update('volume',Number(event.target.value)/100);$('#volume-output').textContent=event.target.value+'%';audio.sync(game.state.running);});
let last=Date.now(),saveElapsed=0,renderElapsed=0,audioCursor=0;setInterval(()=>{const now=Date.now();const dt=(now-last)/1000;last=now;if(!testFrozen)game.tick(dt);saveElapsed+=dt;renderElapsed+=dt;audio.sync(game.state.running);const events=game.eventsSince(audioCursor);if(events.length){audioCursor=events.at(-1).id;if(dt<2&&!document.hidden)audio.playBatch(events);}if(saveElapsed>=5){game.save();saveElapsed=0;}if(renderElapsed>=1){renderElapsed=0;if(page!=='settings')render();}updateCombatHud(game);},100);
window.addEventListener('pagehide',()=>game.save());
render();if(game.state.offlineSummary)toast(game.state.offlineSummary);
if(import.meta.env.DEV){
  window.__ASHEN__={game,scene,audio,preferences};
  Object.defineProperty(window,'__THREE_GAME_DIAGNOSTICS__',{get(){const d=scene.diagnostics();return {renderer:{...d,drawCalls:d.calls},combat:game.combat().phase};}});
  window.__THREE_GAME_TEST_HOOKS__={
    async setState(name){if(name!=='active-play')throw new Error('Unsupported capture state');testFrozen=false;game.act('activity','hunt');page='adventure';render();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {state:name};},
    setPausedForScreenshot(paused){testFrozen=Boolean(paused);}
  };
}

import './gothic.css';

import './classes.css';
import './expedition.css';
